---
title: "Caring for Kalimirchi"
author: "The Deshchangs"
date: "`r Sys.Date()`"
output: html_document
---

## Care guide for Kali

### Feeding and general care

* We wash Kali's water bowl every morning and her food bowl after each meal. She gets filtered tap water.
* Kali currently eats [Taste of the Wild](https://www.chewy.com/taste-wild-pacific-stream-grain-free/dp/181318) kibble
    + We estimate her caloric needs to be around 800 KCal/day
    + Her current kibble has a caloric density of 3.6 Kcal/gram
* On inactive days (e.g. no hiking, no trail running), she should eat **100** grams of kibble in the morning and **100** grams of kibble in the evening (or thereabouts; total **200-210** grams).
    + We feed her in the morning and again in the evening because she cannot ingest enough food in one sitting to meet her caloric requirements.
    + Typically we leave her food out for less than an hour--we are trying to encourage her to not graze on her food through the day.
* On active days, she should eat **100** grams of kibble in the morning and **120** grams of kibble in the evening (total: **220** grams).
* She eats at around 8am in the morning and 6pm in the evening. This is fairly flexible, but she is unlikely to be hungry before 8am.
    + Currently she accepts kibble with some chicken sprinkle in the morning.
    + In the evening, her appetite is usually better and she often eats the kibble plain.
* If these tricks do not work, you can try adding a little bit of vegetable oil (we just use olive oil) to her food, or squeezing some watermelon on top of it, or sprinkling some milk.
* We brush Kali's teeth at night. We wet her toothbrush, squeeze some toothpaste on it, and brush it over her teeth. If that is infeasible, you can put some toothpaste on her kong and let her play with that toy. And you can let her lick and chew at her toothbrush with toothpaste on it.
* We comb Kali once every 2-3 days using the Furminator fur rake.

#### Snacks

* Kali enjoys small treats like the Zuke's training bites
* Kali enjoys eating:
  + watermelon (small pieces)
  + carrot (sometimes, tiny pieces)
  + apple (sometimes, tiny pieces; she likes sweet apples like Honeycrisp rather than tangy ones like Pink Lady)
  + white nectarine (small pieces)
  + banana (small pieces and small quantity)
  + blueberries (sometimes we have to smush one open to entice her)
  + mango (and mango lassi)
  + pear (sweeter varieties)
* We give her treats when she behaves well on walks (we just put some Zuke's treats in a Ziploc bag then give her individual treats on the walk). She gets 1 treat for each instance of good behavior (e.g. ignoring a squirrel that she was inclined to chase).
* She can also have a small fruit or food treat in the afternoon. We typically do not table feed her.

Toxic foods for dogs [include](https://www.akc.org/expert-advice/nutrition/fruits-vegetables-dogs-can-and-cant-eat/):

* cherries
* grapes
* chocolate
* onions
* avocado
* stone fruit pits
* citrus (not toxic but unpleasant for them)

### Commands

Kali knows the following commands. The commands in **bold** have high adherence; *italics*, slightly less adherence; and normal font denotes questionable adherence.

#### Functional commands

* **Curb**
    + A command to remind Kali to sit at the curb before crossing any intersection.
* **Sit**
    + Given with a flat hand facing up
* **Down**
    + Point your hand toward the ground
* **Wait** (useful when you want her to sit/down while you open a door)
    + Point your hand or two fingers toward the ground
* **Stay**
    + Make a flat palm (like a stop sign) with your hand in front of her face
* **Leave it**
    + Used to get her to drop the ball or ignore the exciting squirrel (more difficult)
    + No hand signal
* *Come here*
    + Wave your hand toward your body
* **Release** (to end a successful stay or wait)
* *Stand* (stand up from a down, useful for paw washing)
    + Pull hand up, as though you are opening a drawer
* **Heel**
    + Walk alongside you
    + Reinforced by putting your hand in front of her face and/or shortening the leash
    + Signalled by putting your hand flat in front of her during a walk
* **Take it** (mostly used to get her to eat food)
    + No hand signal
* *Look at me* 
    + useful to obtain Kali's attention when she is distracted by something enticing like a squirrel
    + No hand signal
    + Sometimes we just get up in her face if she is really distracted and make her sit instead of continuing the walk (Walking and chasing the prey is a reward)
* *Point*
    + If you stick out two outstretched fingers in a downward point, Kali should walk to the point
* *Paw* 
    + Gets Kali to untangle herself from her own leash
    + No hand signal
* Don't lick
    + Don't kiss/lick my face
* **Get on**
    + Jump on a sofa or bed
* **Get off**
    + Jump off a sofa or bed
    + No hand gesture; but if she ignores you, you can make a shoving motion with your hands

#### Party tricks

* *Spin*
    + Point fingers together and spin in a circle in front of her snout
* **Gong Xi**
    + Lift hand above her head
* *Shake* 
    + Shake hands
    + First get Kali in a sit position
    + She should know to do this if you extend your hand toward her chest
* Play Bow
    + Point two fingers straight down
* *Crawl*
    + From an incomplete down (body is down but hips are not turned/rolled, like sphinx posture), you gesture forward with your fingers using a treat as a lure
* Roll over
    + She has to be a down position first, then she can be lured to roll over
    + We lure her by having a treat and slowly circling the treat around her head/shoulders
* Weave 
    + walk through legs like weaving poles
* Cross paws
    + Kali has probably forgotten this trick
* Place
    + go to a mat or a specific location
* Speak
    + bark on command; Kali doesn't really know this one yet
* Footsie
    + come between legs and stand on feet

### Walking & Exercise

* Kali goes outside twice a day (on two walks, or a walk + hike or run).
* We ask Kali to sit before we put on her collar and leash to reinforce good, calm behavior.
* In addition to her walks, we let Kali in the backyard first thing in the morning and in the evening after dinner. If we are home, we also let her play in the backyard in the afternoon.
  + Kali may poop in the backyard in the morning before eating and before her walk.
* Kali is an escape artist so she cannot be left in the backyard alone for a long time.
* We take her out in the morning between 7:30am - 10am and typically walk her for 10-20 minutes.
    + Usually Kali will poop on a longer walk.
* Her evening walk happens between 6 - 8pm, depending on temperature and day length. This walk is usually 15-20 minutes.
* Throwing the Chuck-It toy with Kali in the backyard (or a fenced in dog run) is a great way to work out some of her excess energy.
* We do not recommend letting Kali be off leash in an unfenced area. Her recall is spotty.
* If Kali is being unruly on a walk, just stop and have her sit until she calms down. Walking and smelling is the ultimate reward for her, so this is an effective way to deal with things like jumping squirrels.
* When other dogs approach Kali to sniff her, she is usually fine. However, if the other dog is overly excited or a male dog who is larger than her, she may raise her hackles. In this case, Kali can be walked away from that situation. She is generally very calm and does not instigate with other dogs. She does like to try and sniff dogs who are smaller than her.
* We use the foot towel to wipe dirt off her feet. If her paws are really dirty, we use the paw wash.
* To use the paw wash, fill it to the halfway or 3/4 mark with water. One by one, stick each of her feet into the paw washer and gently raise and lower the leg so that the squeegees on the side can remove dirt and mud. Then we squeeze the water out of her fur and dry her off with the foot towel.
* When she has pooped, we wet a paper towel and wipe her bottom and tail (especially where the tail may touch her bottom).

### Emergency care

* Clinic in Saratoga: [Saratoga Veterinary Hospital](https://www.saratogavethospital.com/contact)
    + Contact phone: 408-548-0953
    + Hours: Mon - Sat: 8:00 AM - 8:00 PM; Sun: CLOSED
    + Address: 12297 Saratoga Sunnyvale Road, Suite 100, Saratoga, CA 95070
* First choice emergency hospital: [South Bay Animal Hospital & Pet Resort](http://www.sb-animalhospital.com/)
    + Contact phone: 408-899-4791
    + Should be open 24/7, 365 days a year
    + Address: 5188 Moorpark Ave., San Jose, CA 95129
* Back up emergency hospital: [United Veterinary Specialty and Emergency](http://unitedvet.com/)
    + Contact phone: 408-371-6252
    + Address: 905 Dell Ave, Campbell, CA 95008
    + Secondary Location (open overnight on weekdays and all day on weekends): 601 Showers Drive, Mountain View, CA 94040
* For current and past veterinary information:
    + Veterinarian in Claremont: Dr. Charanpreet Boparai at [Alleve Animal Hospital](http://allevevet.com/staff.php) (check-up in October 2019)
    + Veterinarian in Tennessee: Dr. Cathy Carr at [Powell Animal Hospital](https://www.powellanimalhospital.com/)
    + Dr. Boparai's office should have all of the relevant documents from Kali's treatments in Tennessee. Her only treatment in California was new patient intake and a re-up on standard vaccinations.
  
## Char and Nikhil's contact information in the Philippines

### Itinerary

| Date     | Destination      | Travel specifics | Email/Address      | Phone      |
|----------|:-------------:|:------------:|:----------:|:----------:|
| 3/4      | LAX Airport to Taipei then Cebu Mactan Int'l Airport   | EVA Airways BR 11/281 | deshchang@gmail.com | Booked on Orbitz by c.h.w.chang@gmail |
| 3/6-3/9| Mactan City, Cebu | [AirBnB Unit](https://www.airbnb.com/rooms/15309529) | [Address](https://goo.gl/maps/5Kjm8byHPzMBzDKE7) | Host: Roland Konrad (tel:+639054772059) |
| 3/9      | Mactan Int'l Airport to Coron, Palawan (Busuanga airport) | Cebu Pacific DG 6064 (Time: 7:25 - 9:00) | Booked by deshchang@gmail directly with airline | |
| 3/9-3/11 | Coron, Palawan | [One Averee Bay Hotel](https://goo.gl/maps/kbgDxXrZoGimcAg4A) | Booked by deshchang@gmail.com on Booking.com | +63 919 391 1836 |
|3/11      | Coron (Busuanga) to El Nido, Palawan | [Palawan Days Ferry](https://www.palawandays.com/product/fast-craft-el-nido-coron-busuanga-palawan?) (Time: 12:00pm) | Booked by deshchang@gmail.com directly on their website | +63 977 190 65 00; +6348 434 98 86 |
| 3/11-3/14 | El Nido, Palawan | [Residencia Katrina Bed and Breakfast](https://goo.gl/maps/pQbHR8iH4dor9HQD6)  | Booked by deshchang@gmail on Booking.com | +63 9178089987 |
| 3/14 | El Nido airport to Cebu Mactan Int'l Airport | AirSwift T60336 (Time: 13:00) | Booked by c.h.w.chang@gmail directly on airline's website | +63 917 816 8763 |
| 3/14-3/15 | Cebu City, Cebu | [Hotel Elizabeth Cebu](https://goo.gl/maps/1cW1xVHn1ApFADWB7) | Booked on Agoda by c.h.w.chang@gmail | +63 322318000 |
| 3/15 | Mactan Int'l Airport to Taipei Airport | EVA Airways BR 282 (Time: 11:10am - 14:00) | Booked on Orbitz by c.h.w.chang@gmail | |
| 3/15-3/16|  Layover in Taipei | [iTaipei Service Apartment](https://goo.gl/maps/pSte7nmHpLZLfP9Y9) | Booked by deshchang@gmail on agoda.com | +886225527070 |
| 3/16 | Taipei to LAX | EVA Airways BR 12 (Time: 19:20) | Booked on Orbitz by c.h.w.chang@gmail | |


### Insurance information

* Medical evacuation insurance through [The Standard](https://eservices.europassistance-usa.com/sites/TheStandard/Pages/MembersHome.aspx), also known as Europ Assistance/Generali Global Assistance
    + Phone: +1-240-330-1380 (International hotline)/+1-866-455-9188 (US hotline)
    + Email: ops@gga-usa.com
    + Pomona College (through the Claremont Colleges) group ID: D2STD / Activation code: 181002
    + Pomona College contacts: Cristal.Hernandez@claremont.edu; Angelica.Zaragoza@claremont.edu
* Anthem BlueCross Blue Shield Global Core coverage
    + Group number: 1873JA
    + Coverage through The Claremont Colleges (via Pomona College) for both of us



